#!/usr/bin/env python3
"""Generate hs_tags.h -- the table the shim uses to find SAI functions inside an API struct.

``sai_api_query(api, &tbl)`` hands back a pointer to a struct of function pointers. The shim
patches selected slots of that struct, so it needs, for every object type it can hook, which
API the object lives in and which slot each operation sits at.

Those slots are derivable: in every SAI API struct the four operations of one object type are
four *consecutive* members named ``create_X`` / ``remove_X`` / ``set_X_attribute`` /
``get_X_attribute``, and the bulk pair is ``create_<plural>`` / ``remove_<plural>``. So rather
than hand-maintain ~90 offsets and get one wrong, read them out of the headers.

Run after a SAI bump; the generated header is committed so the shim builds without SAI sources::

    ./gen_tags.py --sai-inc /path/to/sonic-buildimage/src/sonic-sairedis/SAI/inc

Slot safety: syncd stores the pointer the vendor returns and dereferences it using the same
headers we read here, so any slot we touch is one syncd itself would touch. Reading or writing
within this layout is exactly as safe as syncd's own access to it.
"""
import argparse
import os
import re
import sys

OPS = ("create", "remove", "set", "get", "bulk_create", "bulk_remove")

ENUM_RE = re.compile(r"^\s*(SAI_API_[A-Z0-9_]+)\s*=\s*(\d+)\s*,(.*)$")
ENUM_COMMENT_RE = re.compile(r"(sai_\w+_api_t)")
STRUCT_OPEN_RE = re.compile(r"^typedef struct _(sai_\w+_api_t)\s*$")
STATUS_RE = re.compile(r"^#define\s+(SAI_STATUS_[A-Z0-9_]+)\s+"
                       r"(?:SAI_STATUS_CODE\()?(0x[0-9A-Fa-f]+)L?\)?\s*$")
MEMBER_RE = re.compile(r"^\s*(sai_\w+_fn)\s+(\w+)\s*;")

DEFAULT_SAI_INC = [
    os.environ.get("SAI_INC", ""),
    "../../../../../../sonic-buildimage/src/sonic-sairedis/SAI/inc",
]


def find_sai_inc(explicit):
    for path in ([explicit] if explicit else []) + DEFAULT_SAI_INC:
        if path and os.path.isfile(os.path.join(path, "sai.h")):
            return path
    sys.exit("could not find SAI headers; pass --sai-inc <dir containing sai.h>")


def read_api_enum(sai_inc):
    """``{"sai_route_api_t": ("SAI_API_ROUTE", 6)}`` from the sai_api_t enum in sai.h."""
    out = {}
    with open(os.path.join(sai_inc, "sai.h")) as fh:
        for line in fh:
            match = ENUM_RE.match(line)
            if not match:
                continue
            name, value, trailer = match.group(1), int(match.group(2)), match.group(3)
            comment = ENUM_COMMENT_RE.search(trailer)
            struct = comment.group(1) if comment else name.lower().replace("sai_api_", "sai_") + "_api_t"
            out.setdefault(struct, (name, value))
    return out


def read_structs(sai_inc):
    """``{"sai_route_api_t": ["create_route_entry", ...]}`` -- members in declaration order."""
    out = {}
    for entry in sorted(os.listdir(sai_inc)):
        if not entry.endswith(".h"):
            continue
        members, current = [], None
        with open(os.path.join(sai_inc, entry)) as fh:
            for line in fh:
                if current is None:
                    opened = STRUCT_OPEN_RE.match(line)
                    if opened:
                        current, members = opened.group(1), []
                    continue
                if line.startswith("}"):
                    if members:
                        out.setdefault(current, members)
                    current = None
                    continue
                member = MEMBER_RE.match(line)
                if member:
                    members.append(member.group(2))
    return out


def read_status_codes(sai_inc):
    """``{"SAI_STATUS_ITEM_NOT_FOUND": -7}``.

    On anything but Windows SAI_STATUS_CODE(x) is -x, so the header's hex literals are
    negated. SAI_STATUS_SUCCESS is defined bare and stays 0.
    """
    out = {}
    with open(os.path.join(sai_inc, "saistatus.h")) as fh:
        for line in fh:
            match = STATUS_RE.match(line.rstrip())
            if not match:
                continue
            name, literal = match.group(1), int(match.group(2), 16)
            out[name] = -literal if "SAI_STATUS_CODE" in line else literal
    return out


def write_catalog(path, rows, statuses, version, bulk, entries):
    """The same facts as hs_tags.h, for injectors/sai.py to validate specs against."""
    body = [
        '"""Object types and status codes the SAI shim understands.',
        "",
        "Generated by shim/gen_tags.py from the SAI {} headers -- do not edit by hand.".format(version),
        "Having it here is what lets --chaos sai=... reject a typo at configure time, before",
        'any DUT is touched."""',
        "",
        'SAI_VERSION = "{}"'.format(version),
        "",
        "OPS = ({},)".format(", ".join('"{}"'.format(op) for op in OPS)),
        "",
        "OBJECT_TYPES = frozenset({",
    ]
    body += ['    "{}",'.format(tag) for tag, *_ in rows]
    body += ["})", ""]
    body += [
        "# The 20 object types whose API struct carries a bulk create/remove pair. For the other",
        "# 106 there is nothing to hook, so a bulk spec would validate and then silently never",
        "# fire -- which is the false negative the whole lane exists to avoid. Bulk create and",
        "# bulk remove are present or absent together; none of the 126 has just one.",
        "BULK_TYPES = frozenset({",
    ]
    body += ['    "{}",'.format(tag) for tag in bulk]
    body += ["})", ""]
    body += [
        "# Object types whose create takes no output parameter, so dropping the call is safe.",
        "# An object-style create hands back an object id; dropping that one would leave it",
        "# never written and syncd would use uninitialised memory. Read out of the SAI",
        "# declarations, not guessed from the _entry suffix.",
        "ENTRY_TYPES = frozenset({",
    ]
    body += ['    "{}",'.format(tag) for tag in entries]
    body += ["})", "", "STATUS_CODES = {"]
    body += ['    "{}": {},'.format(name, value) for name, value in sorted(statuses.items())]
    body += ["}", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(body))


def entry_style_tags(sai_inc, tags):
    """Object types whose ``create`` takes no output parameter.

    It decides whether ``drop`` is safe. An object-style create is
    ``(_Out_ sai_object_id_t *id, _In_ ...)``: returning success without calling it leaves the
    caller's object id never written, and syncd goes on to use whatever was in that memory. An
    entry-style create is ``(_In_ const sai_route_entry_t *entry, _In_ ...)`` -- nothing is
    handed back, so a dropped call is exactly "the ASIC said yes and did nothing", which is the
    fault worth having.

    Read from the declaration rather than guessed from the ``_entry`` suffix: the suffix happens
    to be reliable today, and a silent mistake here corrupts a running switch.
    """
    out = set()
    for entry in sorted(os.listdir(sai_inc)):
        if not entry.endswith(".h"):
            continue
        text = open(os.path.join(sai_inc, entry)).read()
        for tag in tags:
            match = re.search(
                r"typedef\s+sai_status_t\s+\(\*sai_create_{}_fn\)\s*\(\s*(_\w+_)".format(
                    re.escape(tag)), text)
            if match and match.group(1) != "_Out_":
                out.add(tag)
    return out


def plural(tag):
    return tag[: -len("entry")] + "entries" if tag.endswith("_entry") else tag + "s"


def tags_for(members):
    """Every object type in one API struct, with the slot of each of its six operations."""
    index = {name: slot for slot, name in enumerate(members)}
    found = []
    for slot, name in enumerate(members):
        if not name.startswith("create_"):
            continue
        tag = name[len("create_"):]
        wanted = (name, "remove_" + tag, "set_" + tag + "_attribute", "get_" + tag + "_attribute")
        slots = [index.get(w, -1) for w in wanted]
        if slots != [slot, slot + 1, slot + 2, slot + 3]:
            continue  # not the regular four-in-a-row shape; not worth guessing at
        bulk = plural(tag)
        slots.append(index.get("create_" + bulk, -1))
        slots.append(index.get("remove_" + bulk, -1))
        found.append((tag, slots))
    return found


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sai-inc", help="directory holding sai.h")
    parser.add_argument("-o", "--output", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "hs_tags.h"))
    args = parser.parse_args()

    sai_inc = find_sai_inc(args.sai_inc)
    apis = read_api_enum(sai_inc)
    structs = read_structs(sai_inc)

    rows, skipped = [], []
    for struct, members in sorted(structs.items()):
        if struct not in apis:
            skipped.append(struct)
            continue
        api_name, api_value = apis[struct]
        for tag, slots in tags_for(members):
            rows.append((tag, api_name, api_value, slots, len(members)))
    rows.sort(key=lambda row: row[0])

    if not rows:
        sys.exit("parsed no object types out of {} -- header layout changed?".format(sai_inc))
    clash = {tag for tag, *_ in rows if [r[0] for r in rows].count(tag) > 1}
    if clash:
        sys.exit("object type declared in two APIs: {}".format(", ".join(sorted(clash))))

    version = "unknown"
    try:
        with open(os.path.join(sai_inc, "saiversion.h")) as fh:
            parts = dict(re.findall(r"#define\s+SAI_(MAJOR|MINOR|REVISION)\s+(\d+)", fh.read()))
        version = "{}.{}.{}".format(parts.get("MAJOR"), parts.get("MINOR"), parts.get("REVISION"))
    except OSError:
        pass

    hooks = len(rows) * len(OPS)
    lines = [
        "/* Generated by gen_tags.py from SAI {} headers -- do not edit by hand. */".format(version),
        "#ifndef HS_TAGS_H",
        "#define HS_TAGS_H",
        "",
        '#define HS_SAI_VERSION "{}"'.format(version),
        "#define HS_NUM_TAGS  {}".format(len(rows)),
        "#define HS_NUM_OPS   {}".format(len(OPS)),
        "#define HS_NUM_HOOKS {}  /* HS_NUM_TAGS * HS_NUM_OPS */".format(hooks),
        "",
        "/* Operation order; index into hs_tag_t.slot[]. */",
        "static const char *const hs_op_names[HS_NUM_OPS] = {",
        "    " + ", ".join('"{}"'.format(op) for op in OPS),
        "};",
        "",
        "typedef struct {",
        "    const char *name;   /* object type, e.g. \"route_entry\" */",
        "    int api;            /* sai_api_t value to hook it in */",
        "    int slot[HS_NUM_OPS];  /* member index in the API struct; -1 when absent */",
        "} hs_tag_t;",
        "",
    ]
    used = sorted({row[1]: row[2] for row in rows}.items(), key=lambda kv: kv[1])
    lines.append("/* sai_api_t values used below, so the shim builds without the SAI headers. */")
    lines += ["#define {:<28} {}".format(name, value) for name, value in used]
    lines += ["", "static const hs_tag_t hs_tags[HS_NUM_TAGS] = {"]
    width = max(len(tag) for tag, *_ in rows) + 3
    for tag, api_name, _api_value, slots, _size in rows:
        lines.append('    {{ {:<{w}} {:<26} {{ {} }} }},'.format(
            '"{}",'.format(tag), api_name + ",", ", ".join("{:>3}".format(s) for s in slots), w=width))
    lines += [
        "};",
        "",
        "/* One trampoline per (object type, operation): hook index = tag * HS_NUM_OPS + op. */",
        "#define HS_TRAMPOLINES(X) \\",
    ]
    for start in range(0, hooks, 10):
        chunk = " ".join("X({})".format(n) for n in range(start, min(start + 10, hooks)))
        lines.append("    {}{}".format(chunk, " \\" if start + 10 < hooks else ""))
    lines += ["", "#endif /* HS_TAGS_H */", ""]

    with open(args.output, "w") as fh:
        fh.write("\n".join(lines))
    # Lives beside injector.py, not in shim/: injectors/sai.py validates specs against it,
    # and shim/ is C sources plus a build, not a Python package.
    catalog = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(args.output))),
                           "sai_catalog.py")
    statuses = read_status_codes(sai_inc)
    bulk = [tag for tag, _api, _v, slots, _size in rows if slots[4] >= 0 and slots[5] >= 0]
    entries = sorted(entry_style_tags(sai_inc, [row[0] for row in rows]))
    write_catalog(catalog, rows, statuses, version, bulk, entries)

    print("{}: {} object types, {} hooks, SAI {} (from {})".format(
        args.output, len(rows), hooks, version, sai_inc))
    print("{}: {} object types ({} with bulk, {} entry-style), {} status codes".format(
        catalog, len(rows), len(bulk), len(entries), len(statuses)))
    if skipped:
        print("  no sai_api_t entry, skipped: {}".format(", ".join(sorted(skipped))))


if __name__ == "__main__":
    main()
