/* Generated by gen_tags.py from SAI 1.18.1 headers -- do not edit by hand. */
#ifndef HS_TAGS_H
#define HS_TAGS_H

#define HS_SAI_VERSION "1.18.1"
#define HS_NUM_TAGS  126
#define HS_NUM_OPS   6
#define HS_NUM_HOOKS 756  /* HS_NUM_TAGS * HS_NUM_OPS */

/* Operation order; index into hs_tag_t.slot[]. */
static const char *const hs_op_names[HS_NUM_OPS] = {
    "create", "remove", "set", "get", "bulk_create", "bulk_remove"
};

typedef struct {
    const char *name;   /* object type, e.g. "route_entry" */
    int api;            /* sai_api_t value to hook it in */
    int slot[HS_NUM_OPS];  /* member index in the API struct; -1 when absent */
} hs_tag_t;

/* sai_api_t values used below, so the shim builds without the SAI headers. */
#define SAI_API_SWITCH               1
#define SAI_API_PORT                 2
#define SAI_API_FDB                  3
#define SAI_API_VLAN                 4
#define SAI_API_VIRTUAL_ROUTER       5
#define SAI_API_ROUTE                6
#define SAI_API_NEXT_HOP             7
#define SAI_API_NEXT_HOP_GROUP       8
#define SAI_API_ROUTER_INTERFACE     9
#define SAI_API_NEIGHBOR             10
#define SAI_API_ACL                  11
#define SAI_API_HOSTIF               12
#define SAI_API_MIRROR               13
#define SAI_API_SAMPLEPACKET         14
#define SAI_API_STP                  15
#define SAI_API_LAG                  16
#define SAI_API_POLICER              17
#define SAI_API_WRED                 18
#define SAI_API_QOS_MAP              19
#define SAI_API_QUEUE                20
#define SAI_API_SCHEDULER            21
#define SAI_API_SCHEDULER_GROUP      22
#define SAI_API_BUFFER               23
#define SAI_API_HASH                 24
#define SAI_API_UDF                  25
#define SAI_API_TUNNEL               26
#define SAI_API_L2MC                 27
#define SAI_API_IPMC                 28
#define SAI_API_RPF_GROUP            29
#define SAI_API_L2MC_GROUP           30
#define SAI_API_IPMC_GROUP           31
#define SAI_API_MCAST_FDB            32
#define SAI_API_BRIDGE               33
#define SAI_API_TAM                  34
#define SAI_API_SRV6                 35
#define SAI_API_MPLS                 36
#define SAI_API_DTEL                 37
#define SAI_API_BFD                  38
#define SAI_API_ISOLATION_GROUP      39
#define SAI_API_NAT                  40
#define SAI_API_COUNTER              41
#define SAI_API_DEBUG_COUNTER        42
#define SAI_API_MACSEC               43
#define SAI_API_SYSTEM_PORT          44
#define SAI_API_MY_MAC               45
#define SAI_API_IPSEC                46
#define SAI_API_GENERIC_PROGRAMMABLE 47
#define SAI_API_ARS                  48
#define SAI_API_ARS_PROFILE          49
#define SAI_API_TWAMP                50
#define SAI_API_POE                  51
#define SAI_API_ICMP_ECHO            52
#define SAI_API_PREFIX_COMPRESSION   53
#define SAI_API_SYNCE                54

static const hs_tag_t hs_tags[HS_NUM_TAGS] = {
    { "acl_counter",              SAI_API_ACL,               {   8,   9,  10,  11,  -1,  -1 } },
    { "acl_entry",                SAI_API_ACL,               {   4,   5,   6,   7,  -1,  -1 } },
    { "acl_range",                SAI_API_ACL,               {  12,  13,  14,  15,  -1,  -1 } },
    { "acl_table",                SAI_API_ACL,               {   0,   1,   2,   3,  -1,  -1 } },
    { "acl_table_chain_group",    SAI_API_ACL,               {  24,  25,  26,  27,  -1,  -1 } },
    { "acl_table_group",          SAI_API_ACL,               {  16,  17,  18,  19,  -1,  -1 } },
    { "acl_table_group_member",   SAI_API_ACL,               {  20,  21,  22,  23,  -1,  -1 } },
    { "ars",                      SAI_API_ARS,               {   0,   1,   2,   3,  -1,  -1 } },
    { "ars_profile",              SAI_API_ARS_PROFILE,       {   0,   1,   2,   3,  -1,  -1 } },
    { "bfd_session",              SAI_API_BFD,               {   0,   1,   2,   3,  -1,  -1 } },
    { "bridge",                   SAI_API_BRIDGE,            {   0,   1,   2,   3,  -1,  -1 } },
    { "bridge_port",              SAI_API_BRIDGE,            {   7,   8,   9,  10,  -1,  -1 } },
    { "buffer_pool",              SAI_API_BUFFER,            {   0,   1,   2,   3,  -1,  -1 } },
    { "buffer_profile",           SAI_API_BUFFER,            {  14,  15,  16,  17,  -1,  -1 } },
    { "counter",                  SAI_API_COUNTER,           {   0,   1,   2,   3,  -1,  -1 } },
    { "debug_counter",            SAI_API_DEBUG_COUNTER,     {   0,   1,   2,   3,  -1,  -1 } },
    { "dtel",                     SAI_API_DTEL,              {   0,   1,   2,   3,  -1,  -1 } },
    { "dtel_event",               SAI_API_DTEL,              {  16,  17,  18,  19,  -1,  -1 } },
    { "dtel_int_session",         SAI_API_DTEL,              {   8,   9,  10,  11,  -1,  -1 } },
    { "dtel_queue_report",        SAI_API_DTEL,              {   4,   5,   6,   7,  -1,  -1 } },
    { "dtel_report_session",      SAI_API_DTEL,              {  12,  13,  14,  15,  -1,  -1 } },
    { "fdb_entries",              SAI_API_FDB,               {   5,   6,   7,   8,  -1,  -1 } },
    { "fdb_entry",                SAI_API_FDB,               {   0,   1,   2,   3,   5,   6 } },
    { "fine_grained_hash_field",  SAI_API_HASH,              {   4,   5,   6,   7,  -1,  -1 } },
    { "generic_programmable",     SAI_API_GENERIC_PROGRAMMABLE, {   0,   1,   2,   3,  -1,  -1 } },
    { "hash",                     SAI_API_HASH,              {   0,   1,   2,   3,  -1,  -1 } },
    { "hostif",                   SAI_API_HOSTIF,            {   0,   1,   2,   3,  -1,  -1 } },
    { "hostif_table_entry",       SAI_API_HOSTIF,            {   4,   5,   6,   7,  -1,  -1 } },
    { "hostif_trap",              SAI_API_HOSTIF,            {  12,  13,  14,  15,  -1,  -1 } },
    { "hostif_trap_group",        SAI_API_HOSTIF,            {   8,   9,  10,  11,  -1,  -1 } },
    { "hostif_user_defined_trap", SAI_API_HOSTIF,            {  16,  17,  18,  19,  -1,  -1 } },
    { "icmp_echo_session",        SAI_API_ICMP_ECHO,         {   0,   1,   2,   3,  -1,  -1 } },
    { "ingress_priority_group",   SAI_API_BUFFER,            {   7,   8,   9,  10,  -1,  -1 } },
    { "inseg_entries",            SAI_API_MPLS,              {   4,   5,   6,   7,  -1,  -1 } },
    { "inseg_entry",              SAI_API_MPLS,              {   0,   1,   2,   3,   4,   5 } },
    { "ipmc_entry",               SAI_API_IPMC,              {   0,   1,   2,   3,  -1,  -1 } },
    { "ipmc_group",               SAI_API_IPMC_GROUP,        {   0,   1,   2,   3,   8,   9 } },
    { "ipmc_group_member",        SAI_API_IPMC_GROUP,        {   4,   5,   6,   7,  -1,  -1 } },
    { "ipmc_groups",              SAI_API_IPMC_GROUP,        {   8,   9,  10,  11,  -1,  -1 } },
    { "ipsec",                    SAI_API_IPSEC,             {   0,   1,   2,   3,  -1,  -1 } },
    { "ipsec_port",               SAI_API_IPSEC,             {   4,   5,   6,   7,  -1,  -1 } },
    { "ipsec_sa",                 SAI_API_IPSEC,             {  11,  12,  13,  14,  -1,  -1 } },
    { "isolation_group",          SAI_API_ISOLATION_GROUP,   {   0,   1,   2,   3,  -1,  -1 } },
    { "isolation_group_member",   SAI_API_ISOLATION_GROUP,   {   4,   5,   6,   7,  -1,  -1 } },
    { "l2mc_entry",               SAI_API_L2MC,              {   0,   1,   2,   3,  -1,  -1 } },
    { "l2mc_group",               SAI_API_L2MC_GROUP,        {   0,   1,   2,   3,  -1,  -1 } },
    { "l2mc_group_member",        SAI_API_L2MC_GROUP,        {   4,   5,   6,   7,  -1,  -1 } },
    { "lag",                      SAI_API_LAG,               {   0,   1,   2,   3,  -1,  -1 } },
    { "lag_member",               SAI_API_LAG,               {   4,   5,   6,   7,   8,   9 } },
    { "macsec",                   SAI_API_MACSEC,            {   0,   1,   2,   3,  -1,  -1 } },
    { "macsec_flow",              SAI_API_MACSEC,            {  11,  12,  13,  14,  -1,  -1 } },
    { "macsec_port",              SAI_API_MACSEC,            {   4,   5,   6,   7,  -1,  -1 } },
    { "macsec_sa",                SAI_API_MACSEC,            {  25,  26,  27,  28,  -1,  -1 } },
    { "macsec_sc",                SAI_API_MACSEC,            {  18,  19,  20,  21,  -1,  -1 } },
    { "mcast_fdb_entry",          SAI_API_MCAST_FDB,         {   0,   1,   2,   3,  -1,  -1 } },
    { "mirror_session",           SAI_API_MIRROR,            {   0,   1,   2,   3,  -1,  -1 } },
    { "my_mac",                   SAI_API_MY_MAC,            {   0,   1,   2,   3,  -1,  -1 } },
    { "my_sid_entries",           SAI_API_SRV6,              {  13,  14,  15,  16,  -1,  -1 } },
    { "my_sid_entry",             SAI_API_SRV6,              {   9,  10,  11,  12,  13,  14 } },
    { "nat_entries",              SAI_API_NAT,               {   4,   5,   6,   7,  -1,  -1 } },
    { "nat_entry",                SAI_API_NAT,               {   0,   1,   2,   3,   4,   5 } },
    { "nat_zone_counter",         SAI_API_NAT,               {   8,   9,  10,  11,  -1,  -1 } },
    { "neighbor_entries",         SAI_API_NEIGHBOR,          {   5,   6,   7,   8,  -1,  -1 } },
    { "neighbor_entry",           SAI_API_NEIGHBOR,          {   0,   1,   2,   3,   5,   6 } },
    { "next_hop",                 SAI_API_NEXT_HOP,          {   0,   1,   2,   3,   4,   5 } },
    { "next_hop_group",           SAI_API_NEXT_HOP_GROUP,    {   0,   1,   2,   3,  16,  17 } },
    { "next_hop_group_map",       SAI_API_NEXT_HOP_GROUP,    {  10,  11,  12,  13,  -1,  -1 } },
    { "next_hop_group_member",    SAI_API_NEXT_HOP_GROUP,    {   4,   5,   6,   7,   8,   9 } },
    { "next_hop_groups",          SAI_API_NEXT_HOP_GROUP,    {  16,  17,  18,  19,  -1,  -1 } },
    { "next_hops",                SAI_API_NEXT_HOP,          {   4,   5,   6,   7,  -1,  -1 } },
    { "poe_device",               SAI_API_POE,               {   0,   1,   2,   3,  -1,  -1 } },
    { "poe_port",                 SAI_API_POE,               {   8,   9,  10,  11,  -1,  -1 } },
    { "poe_pse",                  SAI_API_POE,               {   4,   5,   6,   7,  -1,  -1 } },
    { "policer",                  SAI_API_POLICER,           {   0,   1,   2,   3,  -1,  -1 } },
    { "port",                     SAI_API_PORT,              {   0,   1,   2,   3,  23,  24 } },
    { "port_connector",           SAI_API_PORT,              {  15,  16,  17,  18,  -1,  -1 } },
    { "port_llr_profile",         SAI_API_PORT,              {  31,  32,  33,  34,  -1,  -1 } },
    { "port_pool",                SAI_API_PORT,              {   8,   9,  10,  11,  -1,  -1 } },
    { "port_serdes",              SAI_API_PORT,              {  19,  20,  21,  22,  27,  28 } },
    { "port_serdess",             SAI_API_PORT,              {  27,  28,  29,  30,  -1,  -1 } },
    { "ports",                    SAI_API_PORT,              {  23,  24,  25,  26,  -1,  -1 } },
    { "prefix_compression_entry", SAI_API_PREFIX_COMPRESSION, {   4,   5,   6,   7,   8,   9 } },
    { "prefix_compression_table", SAI_API_PREFIX_COMPRESSION, {   0,   1,   2,   3,  -1,  -1 } },
    { "qos_map",                  SAI_API_QOS_MAP,           {   0,   1,   2,   3,  -1,  -1 } },
    { "queue",                    SAI_API_QUEUE,             {   0,   1,   2,   3,  -1,  -1 } },
    { "route_entries",            SAI_API_ROUTE,             {   4,   5,   6,   7,  -1,  -1 } },
    { "route_entry",              SAI_API_ROUTE,             {   0,   1,   2,   3,   4,   5 } },
    { "router_interface",         SAI_API_ROUTER_INTERFACE,  {   0,   1,   2,   3,   7,   8 } },
    { "router_interfaces",        SAI_API_ROUTER_INTERFACE,  {   7,   8,   9,  10,  -1,  -1 } },
    { "rpf_group",                SAI_API_RPF_GROUP,         {   0,   1,   2,   3,  -1,  -1 } },
    { "rpf_group_member",         SAI_API_RPF_GROUP,         {   4,   5,   6,   7,  -1,  -1 } },
    { "samplepacket",             SAI_API_SAMPLEPACKET,      {   0,   1,   2,   3,  -1,  -1 } },
    { "scheduler",                SAI_API_SCHEDULER,         {   0,   1,   2,   3,  -1,  -1 } },
    { "scheduler_group",          SAI_API_SCHEDULER_GROUP,   {   0,   1,   2,   3,  -1,  -1 } },
    { "srv6_sidlist",             SAI_API_SRV6,              {   0,   1,   2,   3,   4,   5 } },
    { "stp",                      SAI_API_STP,               {   0,   1,   2,   3,  -1,  -1 } },
    { "stp_port",                 SAI_API_STP,               {   4,   5,   6,   7,   8,   9 } },
    { "switch",                   SAI_API_SWITCH,            {   0,   1,   2,   3,  -1,  -1 } },
    { "switch_tunnel",            SAI_API_SWITCH,            {   9,  10,  11,  12,  -1,  -1 } },
    { "synce_clock",              SAI_API_SYNCE,             {   0,   1,   2,   3,  -1,  -1 } },
    { "system_port",              SAI_API_SYSTEM_PORT,       {   0,   1,   2,   3,  -1,  -1 } },
    { "tam",                      SAI_API_TAM,               {   0,   1,   2,   3,  -1,  -1 } },
    { "tam_collector",            SAI_API_TAM,               {  32,  33,  34,  35,  -1,  -1 } },
    { "tam_counter_subscription", SAI_API_TAM,               {  44,  45,  46,  47,  48,  49 } },
    { "tam_event",                SAI_API_TAM,               {  40,  41,  42,  43,  -1,  -1 } },
    { "tam_event_action",         SAI_API_TAM,               {  36,  37,  38,  39,  -1,  -1 } },
    { "tam_event_threshold",      SAI_API_TAM,               {  12,  13,  14,  15,  -1,  -1 } },
    { "tam_int",                  SAI_API_TAM,               {  16,  17,  18,  19,  -1,  -1 } },
    { "tam_math_func",            SAI_API_TAM,               {   4,   5,   6,   7,  -1,  -1 } },
    { "tam_report",               SAI_API_TAM,               {   8,   9,  10,  11,  -1,  -1 } },
    { "tam_tel_type",             SAI_API_TAM,               {  20,  21,  22,  23,  -1,  -1 } },
    { "tam_telemetry",            SAI_API_TAM,               {  28,  29,  30,  31,  -1,  -1 } },
    { "tam_transport",            SAI_API_TAM,               {  24,  25,  26,  27,  -1,  -1 } },
    { "tunnel",                   SAI_API_TUNNEL,            {   4,   5,   6,   7,  19,  20 } },
    { "tunnel_map",               SAI_API_TUNNEL,            {   0,   1,   2,   3,  -1,  -1 } },
    { "tunnel_map_entry",         SAI_API_TUNNEL,            {  15,  16,  17,  18,  -1,  -1 } },
    { "tunnel_term_table_entry",  SAI_API_TUNNEL,            {  11,  12,  13,  14,  -1,  -1 } },
    { "tunnels",                  SAI_API_TUNNEL,            {  19,  20,  21,  22,  -1,  -1 } },
    { "twamp_session",            SAI_API_TWAMP,             {   0,   1,   2,   3,  -1,  -1 } },
    { "udf",                      SAI_API_UDF,               {   0,   1,   2,   3,  -1,  -1 } },
    { "udf_group",                SAI_API_UDF,               {   8,   9,  10,  11,  -1,  -1 } },
    { "udf_match",                SAI_API_UDF,               {   4,   5,   6,   7,  -1,  -1 } },
    { "virtual_router",           SAI_API_VIRTUAL_ROUTER,    {   0,   1,   2,   3,  -1,  -1 } },
    { "vlan",                     SAI_API_VLAN,              {   0,   1,   2,   3,  -1,  -1 } },
    { "vlan_member",              SAI_API_VLAN,              {   4,   5,   6,   7,   8,   9 } },
    { "wred",                     SAI_API_WRED,              {   0,   1,   2,   3,  -1,  -1 } },
};

/* One trampoline per (object type, operation): hook index = tag * HS_NUM_OPS + op. */
#define HS_TRAMPOLINES(X) \
    X(0) X(1) X(2) X(3) X(4) X(5) X(6) X(7) X(8) X(9) \
    X(10) X(11) X(12) X(13) X(14) X(15) X(16) X(17) X(18) X(19) \
    X(20) X(21) X(22) X(23) X(24) X(25) X(26) X(27) X(28) X(29) \
    X(30) X(31) X(32) X(33) X(34) X(35) X(36) X(37) X(38) X(39) \
    X(40) X(41) X(42) X(43) X(44) X(45) X(46) X(47) X(48) X(49) \
    X(50) X(51) X(52) X(53) X(54) X(55) X(56) X(57) X(58) X(59) \
    X(60) X(61) X(62) X(63) X(64) X(65) X(66) X(67) X(68) X(69) \
    X(70) X(71) X(72) X(73) X(74) X(75) X(76) X(77) X(78) X(79) \
    X(80) X(81) X(82) X(83) X(84) X(85) X(86) X(87) X(88) X(89) \
    X(90) X(91) X(92) X(93) X(94) X(95) X(96) X(97) X(98) X(99) \
    X(100) X(101) X(102) X(103) X(104) X(105) X(106) X(107) X(108) X(109) \
    X(110) X(111) X(112) X(113) X(114) X(115) X(116) X(117) X(118) X(119) \
    X(120) X(121) X(122) X(123) X(124) X(125) X(126) X(127) X(128) X(129) \
    X(130) X(131) X(132) X(133) X(134) X(135) X(136) X(137) X(138) X(139) \
    X(140) X(141) X(142) X(143) X(144) X(145) X(146) X(147) X(148) X(149) \
    X(150) X(151) X(152) X(153) X(154) X(155) X(156) X(157) X(158) X(159) \
    X(160) X(161) X(162) X(163) X(164) X(165) X(166) X(167) X(168) X(169) \
    X(170) X(171) X(172) X(173) X(174) X(175) X(176) X(177) X(178) X(179) \
    X(180) X(181) X(182) X(183) X(184) X(185) X(186) X(187) X(188) X(189) \
    X(190) X(191) X(192) X(193) X(194) X(195) X(196) X(197) X(198) X(199) \
    X(200) X(201) X(202) X(203) X(204) X(205) X(206) X(207) X(208) X(209) \
    X(210) X(211) X(212) X(213) X(214) X(215) X(216) X(217) X(218) X(219) \
    X(220) X(221) X(222) X(223) X(224) X(225) X(226) X(227) X(228) X(229) \
    X(230) X(231) X(232) X(233) X(234) X(235) X(236) X(237) X(238) X(239) \
    X(240) X(241) X(242) X(243) X(244) X(245) X(246) X(247) X(248) X(249) \
    X(250) X(251) X(252) X(253) X(254) X(255) X(256) X(257) X(258) X(259) \
    X(260) X(261) X(262) X(263) X(264) X(265) X(266) X(267) X(268) X(269) \
    X(270) X(271) X(272) X(273) X(274) X(275) X(276) X(277) X(278) X(279) \
    X(280) X(281) X(282) X(283) X(284) X(285) X(286) X(287) X(288) X(289) \
    X(290) X(291) X(292) X(293) X(294) X(295) X(296) X(297) X(298) X(299) \
    X(300) X(301) X(302) X(303) X(304) X(305) X(306) X(307) X(308) X(309) \
    X(310) X(311) X(312) X(313) X(314) X(315) X(316) X(317) X(318) X(319) \
    X(320) X(321) X(322) X(323) X(324) X(325) X(326) X(327) X(328) X(329) \
    X(330) X(331) X(332) X(333) X(334) X(335) X(336) X(337) X(338) X(339) \
    X(340) X(341) X(342) X(343) X(344) X(345) X(346) X(347) X(348) X(349) \
    X(350) X(351) X(352) X(353) X(354) X(355) X(356) X(357) X(358) X(359) \
    X(360) X(361) X(362) X(363) X(364) X(365) X(366) X(367) X(368) X(369) \
    X(370) X(371) X(372) X(373) X(374) X(375) X(376) X(377) X(378) X(379) \
    X(380) X(381) X(382) X(383) X(384) X(385) X(386) X(387) X(388) X(389) \
    X(390) X(391) X(392) X(393) X(394) X(395) X(396) X(397) X(398) X(399) \
    X(400) X(401) X(402) X(403) X(404) X(405) X(406) X(407) X(408) X(409) \
    X(410) X(411) X(412) X(413) X(414) X(415) X(416) X(417) X(418) X(419) \
    X(420) X(421) X(422) X(423) X(424) X(425) X(426) X(427) X(428) X(429) \
    X(430) X(431) X(432) X(433) X(434) X(435) X(436) X(437) X(438) X(439) \
    X(440) X(441) X(442) X(443) X(444) X(445) X(446) X(447) X(448) X(449) \
    X(450) X(451) X(452) X(453) X(454) X(455) X(456) X(457) X(458) X(459) \
    X(460) X(461) X(462) X(463) X(464) X(465) X(466) X(467) X(468) X(469) \
    X(470) X(471) X(472) X(473) X(474) X(475) X(476) X(477) X(478) X(479) \
    X(480) X(481) X(482) X(483) X(484) X(485) X(486) X(487) X(488) X(489) \
    X(490) X(491) X(492) X(493) X(494) X(495) X(496) X(497) X(498) X(499) \
    X(500) X(501) X(502) X(503) X(504) X(505) X(506) X(507) X(508) X(509) \
    X(510) X(511) X(512) X(513) X(514) X(515) X(516) X(517) X(518) X(519) \
    X(520) X(521) X(522) X(523) X(524) X(525) X(526) X(527) X(528) X(529) \
    X(530) X(531) X(532) X(533) X(534) X(535) X(536) X(537) X(538) X(539) \
    X(540) X(541) X(542) X(543) X(544) X(545) X(546) X(547) X(548) X(549) \
    X(550) X(551) X(552) X(553) X(554) X(555) X(556) X(557) X(558) X(559) \
    X(560) X(561) X(562) X(563) X(564) X(565) X(566) X(567) X(568) X(569) \
    X(570) X(571) X(572) X(573) X(574) X(575) X(576) X(577) X(578) X(579) \
    X(580) X(581) X(582) X(583) X(584) X(585) X(586) X(587) X(588) X(589) \
    X(590) X(591) X(592) X(593) X(594) X(595) X(596) X(597) X(598) X(599) \
    X(600) X(601) X(602) X(603) X(604) X(605) X(606) X(607) X(608) X(609) \
    X(610) X(611) X(612) X(613) X(614) X(615) X(616) X(617) X(618) X(619) \
    X(620) X(621) X(622) X(623) X(624) X(625) X(626) X(627) X(628) X(629) \
    X(630) X(631) X(632) X(633) X(634) X(635) X(636) X(637) X(638) X(639) \
    X(640) X(641) X(642) X(643) X(644) X(645) X(646) X(647) X(648) X(649) \
    X(650) X(651) X(652) X(653) X(654) X(655) X(656) X(657) X(658) X(659) \
    X(660) X(661) X(662) X(663) X(664) X(665) X(666) X(667) X(668) X(669) \
    X(670) X(671) X(672) X(673) X(674) X(675) X(676) X(677) X(678) X(679) \
    X(680) X(681) X(682) X(683) X(684) X(685) X(686) X(687) X(688) X(689) \
    X(690) X(691) X(692) X(693) X(694) X(695) X(696) X(697) X(698) X(699) \
    X(700) X(701) X(702) X(703) X(704) X(705) X(706) X(707) X(708) X(709) \
    X(710) X(711) X(712) X(713) X(714) X(715) X(716) X(717) X(718) X(719) \
    X(720) X(721) X(722) X(723) X(724) X(725) X(726) X(727) X(728) X(729) \
    X(730) X(731) X(732) X(733) X(734) X(735) X(736) X(737) X(738) X(739) \
    X(740) X(741) X(742) X(743) X(744) X(745) X(746) X(747) X(748) X(749) \
    X(750) X(751) X(752) X(753) X(754) X(755)

#endif /* HS_TAGS_H */
